apiVersion: v1
kind: Service
metadata:
  name: krakend
  namespace: devops-monitoring
  labels:
    app.kubernetes.io/name: krakend
spec:
  type: NodePort
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30010
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: krakend