apiVersion: v1
kind: Service
metadata:
  name: krakend
  namespace: krakend
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8080
    protocol: TCP
    nodePort: 30010
  selector:
    app: krakend
