apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: krakend
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: devopsfaith/krakend:2.9.3
        ports:
        - containerPort: 8080
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.tmpl", "-p", "8080" ]
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend
        - name: krakend-final-config
          mountPath: /etc/krakend-final
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
        env:
        - name: KRAKEND_PORT
          value: "8080"
        - name: FC_ENABLE
          value: "1"
        - name: FC_OUT
          value: "/etc/krakend-final/salida.json"
        #- name: FC_TEMPLATES
        #  value: " /etc/krakend"

      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
      - name: krakend-final-config
        emptyDir: {}
