apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-monitoring

resources:
- ../base

patchesStrategicMerge:
- deployment.yaml

configMapGenerator:
- files:
  - krakend.json
  name: krakend-config

generatorOptions:
  disableNameSuffixHash: false
