apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: krakend

resources:
- ../base

patches:
- path: deployment.yaml

configMapGenerator:
- files:
  - krakend-config/krakend.tmpl
  - krakend-config/settings.tmpl
  - krakend-config/telemetry.tmpl
  - krakend-config/endpoints.tmpl
  - krakend-config/backends.tmpl
  - krakend-config/backends/combined.tmpl
  - krakend-config/backends/limited.tmpl
  - krakend-config/backends/todos.tmpl
  - krakend-config/backends/weather.tmpl
  name: krakend-config

generatorOptions:
  disableNameSuffixHash: false
