apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-monitoring

resources:
- ../krakend/base

patchesStrategicMerge:
- krakend/deployment.yaml

configMapGenerator:

- name: krakend-config
  files:
    - krakend/krakend.ini

generatorOptions:
  disableNameSuffixHash: false
