apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: krakend

resources:
- ../krakend/base

patches:
- path: krakend/deployment.yaml

configMapGenerator:

- name: krakend-config
  files:
    - krakend/krakend-config/krakend.tmpl
    - krakend/krakend-config/settings.tmpl
    - krakend/krakend-config/telemetry.tmpl
    - krakend/krakend-config/endpoints.tmpl
    - krakend/krakend-config/backends.tmpl
    - krakend/krakend-config/backends/combined.tmpl
    - krakend/krakend-config/backends/limited.tmpl
    - krakend/krakend-config/backends/todos.tmpl
    - krakend/krakend-config/backends/weather.tmpl

generatorOptions:
  disableNameSuffixHash: false
